version: 2.1

jobs:
  build_and_push_ecr:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker  
      - checkout

      
      - run:
          name: Install AWS CLI
          command: |
            apk update
            apk add --no-cache aws-cli

      
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION

      
      - run:
          name: Ensure ECR Repository Exists
          command: |
            aws ecr describe-repositories --repository-names $ECR_REPOSITORY_NAME || \
            aws ecr create-repository --repository-name $ECR_REPOSITORY_NAME

      
      - run:
          name: Log in to Amazon ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      
      - run:
          name: Build and Push Docker Image to ECR
          command: |
            docker build -t my-app ./frontend  
            docker tag my-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest

workflows:
  version: 2
  ecr_deployment:
    jobs:
      - build_and_push_ecr
