version: 2.1

jobs:
  build_and_push_ecr:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker  # Removed version to use the default supported Docker version
      - checkout

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            apk update
            apk add --no-cache aws-cli

      # Configure AWS CLI with Environment Variables
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION

      # Log in to Amazon ECR
      - run:
          name: Log in to Amazon ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # Build and Push Docker Image
      - run:
          name: Build and Push Docker Image to ECR
          command: |
            docker build -t my-app .
            docker tag my-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest

workflows:
  version: 2
  ecr_deployment:
    jobs:
      - build_and_push_ecr
